### ISSUE TITLE
最新活动卡图下载问题

### ISSUE THREAD

**Issue by srwgin** [toyobayashi/mishiro#11]
2张活动卡 4张图 和 开始游戏页面的活动图
下载下来是全白的

**Comment by toyobayashi** [comment]
@srwgin
已确认。问题出在新卡的 Unity 文件格式版本更新了，我一时半会儿不会弄，先切换回从starlight.kirara.ca获取图片吧

**Comment by toyobayashi** [comment]
@srwgin 可以更新了。把空白图片删掉再启动

**Comment by srwgin** [comment]
OK 暂时能下图了

**Comment by srwgin** [comment]
顺便问下 百万土豆 有类似你这个一样的 下图  下歌曲 下语音的 工具吗 谢谢

**Comment by toyobayashi** [comment]
@srwgin 百万土豆我没有研究过，CGSS也弃坑好久了，没有时间肝

**Comment by toyobayashi** [comment]
1.9.0 新增图片获取源选项
