### ISSUE TITLE
下载列表的问题

### ISSUE THREAD

**Issue by Wanchet1** [toyobayashi/mishiro#12]
请问，有没有让搜索列表只显示未下载文件的方法？
每次都要为了新文件翻好几百页，感觉手快要撑不住了

**Comment by toyobayashi** [comment]
@Wanchet1 我有时间的话，可以弄一下。目前只是已下载的文件不能勾选

**Comment by Wanchet1** [comment]
更新之后，拯救了我的右手，感谢大神
另外想请教一个别的音游的下载问题，ameba的ガルフレ音，我用抓包工具找到了某些文件的下载链接和在启动时下载过一个566K大小的加密zip包，里面有一个tmp/dbaa。（https://cdn.gf-music.amebagames.com/1482907171/assets/dbaa?x=1558966203）
我想问一下，像这种游戏还有别的获取下载列表的途径吗？或者有什么得到密码的方式吗？反编译之类的完全没研究过，所以卡在这里很长时间了，希望大神能指点一下（跪

**Comment by toyobayashi** [comment]
@Wanchet1 每个游戏都不一样的啦，我没研究过你这个。CGSS我也是研究了好久服务器加密通信还有音频拆包解码啥的，参考真·大神的代码才做出来mishiro

**Comment by Wanchet1** [comment]
问题是ameba家的这个，除了疑似资源列表的文件打包加密之外，其他的文件都没有加密，甚至能用电脑浏览器下载下来，连浏览器标识都不检查的（捂脸
我想问一下，以您的经验来看，dbaa是不是资源列表啊？压缩包里面的文件大概1.9M，如果是的话，我就去想办法拆他了
顺便说下动机：这游戏我感觉从我开始玩到现在就没更新过，贴吧里也说已经出完最后一首歌了，所以想把东西都下下来。还有一点就是，之前玩的时候没挂梯子，后来挂梯子上了次Google游戏，然后存档居然回档了！！？（捂脸

**Comment by toyobayashi** [comment]
@Wanchet1 emmmmm....从db这两个字看这东西可能是个数据库吧w
