### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fina07** [toyobayashi/mishiro#13]
![Screenshot (34)](https://user-images.githubusercontent.com/51048083/58380686-a4775380-7fe6-11e9-9c12-f75fb1bcbed0.png)

Hello, I've this error when load mishiro
any fix or suggestion??

**Comment by toyobayashi** [comment]
@Fina07 The error didn't occur when I tested. Maybe it's the problem from your network or HTTPS certificate. Sorry, I have no idea. You can try to reinstall mishiro.

**Comment by Fina07** [comment]
@toyobayashi I can use my network normally tho. I've try reinstall and use older ver but it give me same error...ur program seem really nice to use! It's too bad i can't use it... Do u've any similiar program to rip from cgss?

**Comment by toyobayashi** [comment]
@Fina07 Try mishiro 1.9.0? Run mishiro on another computer? Similar programs are listed in readme of this repository's Reference part. you can also search "Deretore" on github.

**Comment by Fina07** [comment]
@toyobayashi I've tried another pc and it's worked! did u've option to download everything instead download only in current page?  really appreciate ur hardwork~

**Comment by Fina07** [comment]
@toyobayashi btw did y'know wut the live bg video name?

**Comment by toyobayashi** [comment]
@Fina07 Downloading everything is not supported considering performance and security. 

> btw did y'know wut the live bg video name? and what the function for gacha sim?

I don't know video name. The function for gacha sim is just test your recent luck.

**Comment by Fina07** [comment]
@toyobayashi have u try import the unity3d to asset studio/unity studio? I try export from asset studio and the uv map was really mess up ;V;
