### ISSUE TITLE
Stuck while downloading

### ISSUE THREAD

**Issue by MarieRose1301** [toyobayashi/mishiro#14]
Hello, I've tried to download the new version after a long time of not using the program, and after I open it, it downloads 2 files, and gets stuck at 100% at the second file, is there anything I can do to fix this?
![image](https://user-images.githubusercontent.com/20154978/60394665-b477db00-9b30-11e9-9521-5591b11c6fb6.png)

**Comment by toyobayashi** [comment]
@MarieRose1301 Uninstall older mishiro completely first and try again.

**Comment by Mejax** [comment]
> 
> 
> @MarieRose1301 Uninstall older mishiro completely first and try again.

i encountered the same problem and tried what you have suggested... so in my case it doesnt work my friend. i uninstalled completely and checked on the installation folder for 5 times and installed again same problem.

but just to help, here is my network packet interception to help you find the problem
GET /dl/resources/AssetBundles/65/658959d9536a5969d678f77ff9bc2d22 HTTP/1.1
X-Unity-Version: 2018.3.8f1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; LG-F500K Build/NRD90U)
Host: asset-starlight-stage.akamaized.net
Connection: Keep-Alive
Accept-Encoding: gzip

GET /dl/resources/Sound/7e/7e399284a465be3213ca0ff272d3b851 HTTP/1.1
X-Unity-Version: 2018.3.8f1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; LG-F500K Build/NRD90U)
Host: asset-starlight-stage.akamaized.net
Connection: Keep-Alive
Accept-Encoding: gzip

GET /dl/resources/Sound/72/72c3f7cd844cc404d83802a4b6d8726d HTTP/1.1
X-Unity-Version: 2018.3.8f1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; LG-F500K Build/NRD90U)
Host: asset-starlight-stage.akamaized.net
Connection: Keep-Alive
Accept-Encoding: gzip

**Comment by Mejax** [comment]
update:
just for experiment, i tried copying 

> X-Unity-Version: 2018.3.8f1
> User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; LG-F500K Build/NRD90U)
> Host: asset-starlight-stage.akamaized.net
> Connection: Keep-Alive
> Accept-Encoding: gzip
> 

used it on fiddler, then open the manifest.csv via note pad (the manifest.csv came from manifest_(some number here).db that is downloaded by mishiro and inside the manifest table which is exported to *.csv by db browser), select a target cgss unity 3d file, for example the new cinfest fumika model (head), copy the hash which is in case, 5c4e84d0e2b609e3aeb2a5c7574cd3ca, copy also the first 2 letters of the hash, and make it look like this /5c/5c4e84d0e2b609e3aeb2a5c7574cd3ca and and paste it at the end of https://asset-starlight-stage.akamaized.net/dl/resources/AssetBundles**/5c/5c4e84d0e2b609e3aeb2a5c7574cd3ca** execute fiddler, save response, extract the unity file using some lz4 decompress and it works. 

of course, your mishiro is better a million times and easier too. this workaround is too tedious and tiring specially if there's a need to download multiple or all models for 3d rips and backups

**Comment by toyobayashi** [comment]
Now I have known the reason. I will fix it in `v1.9.1`.

**Comment by Mejax** [comment]
> 
> 
> Now I have known the reason. I will fix it in `v1.9.1`.

excellent and thank you! now testing :D

**Comment by toyobayashi** [comment]
@Mejax Thank you all the same! If similar problem occur in the future, you can try launch mishiro in command line, errors will be logged out.

**Comment by Mejax** [comment]
running mishiro in command line <<< guide please my friend so the next time errors pop out, i could post the log instead here. i frequently use your application (since i rip models to convert for use to MMD) so i am sure i will be encountering this errors frequently

**Comment by toyobayashi** [comment]
@Mejax 

Here gives two ways to open command line. (Windows)

1. `win + R` and enter `cmd`.
2. Open mishiro folder, then edit the path of explorer to `cmd` and press `Enter`.

Check whether the `Current Working Directory` is your mishiro install folder.

if it is, enter `mishiro` directly and press `Enter` to run mishiro.

```
C:\somewhere\you\install\mishiro>mishiro
```

else you can use `cd` command to change CWD:

```
C:\Windows\system32>cd ../..
C:\>cd somewhere/you/install/mishiro
C:\somewhere\you\install\mishiro>mishiro
```

By the way, you can enter `dev` in mishiro [HOME] to open chrome devtools. Switch to `Console` tab to confirm if there is some errors logged out. It may help as well.

**Comment by MarieRose1301** [comment]
It works now, thank you so much
