### ISSUE TITLE
大佬，是否可以建立releases的国内镜像源？

### ISSUE THREAD

**Issue by jpysina** [toyobayashi/mishiro#15]
如题。去年从贴吧过来的，一直在这边使用已经编译的win64版本使用，几个月来大佬的基于electron的mishiro一如既往地好用，十分感谢！

然而github的release目前处于不稳定状态，从6月起下载基本处于不可用的状态，无法完成下载。

坐标为江苏苏州。另请求了上海、杭州、浙江湖州、嘉兴、宁波、江苏南京、常州、无锡的几个小伙伴一起测试，运营商为电信、移动。即使使用科学上网，他们也均反馈表示有同样的问题存在；尤其是移动的，都下到一半不到就挂了.......

使用科学上网的方法试图解决(v*p*n、SS、SSR都试过)，但速度未有改善，也不能完成下载。下载器是使用IDM、FDM、浏览器自带下载器、迅雷。

大致如下图所示：
![image](https://user-images.githubusercontent.com/26199978/60756825-08a12480-a035-11e9-94df-8ab44c3eef49.png)

毕竟，github是基于亚马逊的云服务（AWS），它的s3服务器在国内并无CDN加速，因此访问外网自然就比较慢。由于常规改host的方法目前已经基本失效，因此速度自然提不上去。

因此，我的诉求（建议）是**建立国内的release镜像源**，在中文版readme上添加指向链接，我这里有几个不成熟的方案，大佬看看是否可以采纳？如果已经实施，还请在readme上给出明显链接

**1. 国内网盘**

           =>pan.baidu.com;        //喜闻乐见的百度盘（方便管理，但是有限速）
           =>www.lanzou.com;    //不限速的蓝奏云，有大小限制，可能要分卷（速度快）
    ----------------------------------------------------------------------------
           ->如果考虑到被度盘抽掉的风险，还请打成加密压缩包，密码放在readme中;
           ->使用网盘法有助于为国内网友更快提供信息，但是不利于git版本管理，需要额外的建制
==============================================================
**2.开源中国的码云或者其它国内代码托管网站[参见下面的1号链接]**
           这是github的国内版，因为建立在国内，有CDN加成，所以无论是代码还是其他都访问相对较快，我的建议是大佬是否可以将此项目直接移植到码云上作为国内的副本，在该托管网站上发布release的镜像，方便国内用户下载？在国内政策日益严格的趋势下，科学上网的难度只会越来越大，也越来越不成为现实和主要手段。

           建议大佬在本地写完程序后与github同步、编译后传入github；码云这边貌似可以直接同步github上的改动，方便管理。其修改的路由模式大致如下：

                  用户（大佬）====>Github======>码云

          只是，release需要额外手动上传一次。至少我已经尝试fork大佬的整个项目到码云（已删）后，只有代码，没有可用的release。

=============================================================
**不知大佬意下如何？还请动动手，帮助一下我等萌新可好？**

> 参考文献：
[1]**解决GitHub下载慢问题，不用修改HOSTS文件
https://blog.csdn.net/github_37847975/article/details/86477343；
（笔者注：其中的host方法已没有效果，建议大佬使用↑此文↑中的第二条方法）**
[2] https://www.v2ex.com/amp/t/530884；
（笔者注：挂全局梯子现在也下载不了）
[3]解决下载GitHub项目速度慢的问题（2019.1.21亲测有效）https://blog.csdn.net/github_37847975/article/details/86477343；
[4]下载github的release文件过慢的解决方法 
https://gadzan.com/wget-downloading-github-s-release-files/
（笔者注：wget-win 不能下载release中的文件）
[5]解决GitHub release文件被墙下载失败问题
https://www.jianshu.com/p/8e931a47cd96
（笔者注：host基本无效、pcloud无法注册、无法访问、科学上网后无法转存）；

**Comment by toyobayashi** [comment]
@jpysina 

感谢支持！贴吧基本不上了，有什么需求或者建议直接来开issue就好，有时间能弄我就弄一下。

其实很久以前我在码云上同步过一份代码，只不过用的是私有仓库。以前把大文件弄进了提交历史用尽各种方法都删不掉，导致仓库有85M，用github拉代码也是慢到不行，还是因为菜（手动捂脸

github release 下载不了的话，我把码云的仓库公开在那边再上传就好了，到时候我把地址放到readme里。度盘需要的话我也会弄一份。如果是mac用户很抱歉只能自己编译，因为我没有mac电脑也没测过mac上能不能编译成功。

cgss我已经退坑很久了，但是看到mishiro有越来越多的人开始使用，这个项目我也还在抽时间维护（以前写的代码太烂了真想重构），你们的支持会变成我的动力，虽然我现在我依然很菜

**Comment by jpysina** [comment]
恩恩。说实话，CGSS我这边主要还是和大佬差不多（不打歌也不玩，其实就是退坑了），现主要以使用解包的资源为主。我这边也是研究unity用到的。凭借着南宫梦较为优秀的美工资源以及大佬这两年的不断维护，我们才能拿到资源实现我们夜夜念想的东西。因此，相较于CGSS的各类wiki，大佬无疑是更为底层的帮助了我们。

另外虽然说我对mishiro的用法是当做“The resources downloader for CGSS with GUI”用，也不止一次地想要是能把mishiro的几个core方法封装成C# dll该有多好（我自己是学.net的）但不管怎么说，之前的诉求大佬能够满足，我等已十分感激。

国内节点这边，速度体验十分良好，使用普通下载器效果奇快无比，感谢！
![image](https://user-images.githubusercontent.com/26199978/60770532-550c6300-a10e-11e9-8283-d081fcfaf76d.png)

那么，之后的日子里咱们多互相支持哈~
我先去看zen2评测啦，AMD Yes！

**有个小bug，虽然我自己觉得可能吹毛求疵了：**
![image](https://user-images.githubusercontent.com/26199978/60770580-027f7680-a10f-11e9-8ef9-c5e602714cb7.png)
![image](https://user-images.githubusercontent.com/26199978/60770590-15924680-a10f-11e9-8540-d35144433769.png)

对于码云的描述建议：**简体中文readme描述**增加“中国大陆地区推荐”（或者“国内镜像”）的字样，为萌新引导道路，大佬觉得如何呢？这个就不pull request啦~

**Comment by toyobayashi** [comment]
@jpysina 能帮上忙就好。想问一下你们在做什么项目呢？还有你想把什么功能弄成C#的DLL呢？mishiro-core的核心功能都用的C++，hca解码啊转MP3这些，把C++编译成dll给C#调不行吗

**Comment by jpysina** [comment]
倒也是。不过与你巧了，我C++也很烂，看到指针就懵逼的那种......我不是学软件工程的，本专业是做景观设计的。在我们那边有个设计工具叫做“Rhinoceros”，它支持python和C#，这段时间我是在学习拿它官方的SDK文档开发插件，实现一些自动设计逻辑和类似于退火算法这种可以使用规划求最优解的技术。另一方面，我这边也在研究unity，U3D场景建模可能是以后重点学习的目标，为了一些非真实性渲染表达效果需要，扔几个CGSS的偶像模型进去当做人体试着玩玩（个人兴趣哈哈哈哈）。其实说白了就是相比其他的同事来说我更想偷懒，想自动求解自动画图，现在看来时间消耗更多了[#滑稽]

之前说到那个C++封装成dll我估计是我一时沙雕了，到时候我回去用VS去build下给C#调用，这么做主要是想做一个纯粹的Downloader自用，不过现在想想也没时间，还是继续学SDK和U3D要紧。

不过就我对mishiro的下载功能，之前念想着做C#版Downloader也有一些想法，我再整理整理，到时候看看能不能再交流交流,整理好了会以新的issue传送哈

那么，我先关掉这个issue啦~

**Comment by toyobayashi** [comment]
给大佬端茶

**Comment by jpysina** [comment]
过奖了过奖了，说实话我也是半斤八两，本着不要造轮子的心态东拼西凑才弄出来的，不管如何咱们互相加油啊
