### ISSUE TITLE
请问3d模型文件有没有对应于卡面序号的列表

### ISSUE THREAD

**Issue by spdv123** [toyobayashi/mishiro#18]
在资源窗口中搜索3d_开头的文件head，body的序号难以对应到角色，为了避免全部下载然后一一查看，想请问一下有没有已知的对应列表，谢谢

**Comment by toyobayashi** [comment]
@spdv123 不好意思哈，这个我没研究过也不太清楚

**Comment by spdv123** [comment]
找到解决方法了😂
1. 在master数据库card_data表中根据卡片id找到对应的chara_id
![image](https://user-images.githubusercontent.com/13232524/62591803-6316f480-b903-11e9-939d-c4c14e1b7549.png)
2. 然后去manifests库manifests表中查询"3d_chara_head_"+4位前导0的chara_id
![image](https://user-images.githubusercontent.com/13232524/62591866-a40f0900-b903-11e9-94d2-e0240e37f6b9.png)
这些.unity3d文件是各个皮肤的头部mesh+texture
圈起来的部分是皮肤的id
3. 以1601为例
再下载3d_tx_body1601_hq.unity3d和3d_md_body1601_hq.unity3d文件即可获得身体部分的texture和mesh

不过身体对应的AnimationClip资源应该是通用的没有存在身体部分的unity3d文件中，还没找到
