### ISSUE TITLE
OneShin Solos

### ISSUE THREAD

**Issue by mxze** [toyobayashi/mishiro#19]
Hello! So a new feature was just added that allows you to mix solo versions of Onegai! Cinderella so that each voiced girl on stage will be actually singing her part in the Grand MV. I wanted to get the solo voice files for all of the girls, and it seems like two files are needed for each solo, a .acb file and a .awb file. The problem is is that I can't download the .awb ones through mishiro, and attempting to manually decode the .acb files seems like it can't be done without the .awb file. The same problem happens if I try to download it through the LIVE screen on mishiro; the files are unable to decode and I only get the .acb downloaded.

I hope there is a fix for this; I'd love to hear their solos from the Grand version.

**Comment by toyobayashi** [comment]
@mxze
Fixed in 2.0.0-pre2.

**Comment by mxze** [comment]
It works fine now, thank you so much!
