### ISSUE TITLE
Download all assets from manifest

### ISSUE THREAD

**Issue by SysVR** [toyobayashi/mishiro#27]

**Comment by toyobayashi** [comment]
Could you please provide more description?

**Comment by SysVR** [comment]
オプションに、「一括ダウンロード」
ボタンをつけて欲しいです。
master.mdb、manifest.mdbと
manifest.dbに記載されているすべてのファイルを
lz4の解凍及びwavファイルにデコードしません。

ファイルを一括ダウンロードする場合
ファイルのハッシュをチェックし
ファイルが一致しない（存在しない）場合はダウンロードされます。

asset-starlight-stage.akamaized.net/以下をdl/BatchDownload/に保存。

私は間違えて
https://toyobayashi.github.io/2018/04/01/CGSS%E6%A1%8C%E9%9D%A2%E5%BA%94%E7%94%A8mishiro%E8%83%8C%E5%90%8E%E7%9A%84%E6%95%85%E4%BA%8B/
にコメントしてしまった。
すみません。

**Comment by toyobayashi** [comment]
こちらこそすみません、ブログのコメントは通知がなくて気づきませんでした。要望は大体わかりましたが、最近しごともいろいろ忙しくておそらくこの機能は来年実装の予定になります。日本語が苦手ですみません

**Comment by SysVR** [comment]
日本語に変な箇所はありません。
了解しました。

**Comment by toyobayashi** [comment]
v2.2.0 released, close.
