### ISSUE TITLE
映像やアセットについて。

### ISSUE THREAD

**Issue by SysVR** [toyobayashi/mishiro#28]
vr_unload_se_story10040は非圧縮lz4アーカイブです。

04 05 06 07    08 09 0A 0B が同一で 0Cが00だと非圧縮みたいです。(多分0Cが01だと圧縮。00だと非圧縮。フォーマットとか見てないただの勘ですｗ）

映像はusm形式はデコードできます。(ソースコード付き)
CRI_USM_Decrypter_v1.01.zip 
https://drive.google.com/drive/folders/129sNmot0AJKsgn3uxa3JRhnFyq9PqFoe

キーはHCAと同じです。
ちなみに映像は1920x1088で正常です。
下に8ピクセル黒帯があります。

で、ffmpeg等を使って再エンコードしないとだめです。
ffmepgを利用する場合は、2パスエンコードで、

ffmpeg -i <m2v path> -pass 1 -y -c:v libx264 -vf crop=1920:1080:0:0 outputfile.mp4
ffmpeg -i <m2v path> -i <wav path> -pass 2 -y -c:v libx264 -preset slow -b:v 2700K -c:a aac -b:a 160000 -vf crop=1920:1080:0:0 outputfile.mp4

がベストです。
(2700Kbpsっていうのは各種デレステの動画ファイルの平均ビットレートが2700Kbpsだったので)

**Comment by toyobayashi** [comment]
ありがとうございます！大変助かりました！！！

**Comment by toyobayashi** [comment]
2.3.1 released, close.
