### ISSUE TITLE
there arent all the stages files up to download?

### ISSUE THREAD

**Issue by SouleaterLCC** [toyobayashi/mishiro#31]
i really want the stage kawai make my day stage it only have the meshes and the textures but it doesnt have the animator? why? its listed in your program but it cant be downloaded, can you help me with this please?

**Comment by SouleaterLCC** [comment]
> i really want the stage kawai make my day stage it only have the meshes and the textures but it doesnt have the animator? why? its listed in your program but it cant be downloaded, can you help me with this please?

**Comment by toyobayashi** [comment]
@SouleaterLCC Could you please tell me which file can not be downloaded?
