### ISSUE TITLE
一括ダウンロード・エラー

### ISSUE THREAD

**Issue by SysVR** [toyobayashi/mishiro#32]
一括ダウンロードでエラーが発生した場合にダウンロードが中断されてしまいます。
エラーが発生した場合でもそのまま継続してダウンロードを行い、
最後にエラーが発生したファイル名を列挙すればいいと思います。

**Comment by toyobayashi** [comment]
暇があったら修正します。

**Comment by toyobayashi** [comment]
v2.4.0 has been released.
