### ISSUE TITLE
複数選択などの要望

### ISSUE THREAD

**Issue by SysVR** [toyobayashi/mishiro#34]
Liveなどの検索結果で、
Ctrl+やShiftを押しながら複数選択できるようにして欲しいです。
Liveの場合は複数ファイルのデコードを行います。
複数ファイルの場合は進行バーに[現在/選択個数]
と表示し、×ボタンを表示。

オプションで音の変換形式を選べるようにしてほしい。
wav,mp3,aac
aacは160kbps(ファイルサイズが展開済みacbと同等)

歌詞はlrcファイルにする。
https://ja.wikipedia.org/wiki/LRC_(file_format)

**Comment by toyobayashi** [comment]
中国語訳：
- Live 搜索结果支持 ctrl/shift 复选和多文件解码
- 通过选项控制音频输出格式 wav/mp3/aac
- 支持歌词导出 lrc 格式

次のマイナーバージョンで実装します。（いつできるかわかりません）

**Comment by SysVR** [comment]
ありがとうございます。
よろしくお願いします。

**Comment by toyobayashi** [comment]
[2.5.0](https://github.com/toyobayashi/mishiro/releases/tag/v2.5.0) released, close this. Feel free to open another issue if you meet any problem.
