### ISSUE TITLE
cgss新版本资源解包相关

### ISSUE THREAD

**Issue by arbalest876** [toyobayashi/mishiro#37]
cgss更新了unity版本（unity2020.3.8f1），用UABE无法读取文件。UABE已经很久没更新了，所以能考虑下mishiro增加解包资源功能么（现在只能选择卡片编号解出对应的卡片图）？

**Comment by toyobayashi** [comment]
@arbalest876 我并不熟悉u3d解包，现有的工具都做得比我这个门外汉好很多，建议可以试试[AssetStudio](https://github.com/Perfare/AssetStudio)

**Comment by arbalest876** [comment]
可以用，感谢！
