### ISSUE TITLE
部分歌曲无法正常播放

### ISSUE THREAD

**Issue by somapoke** [toyobayashi/mishiro#38]
举个例子：“LIVE-2043到2047的曲目下载完毕后点击PLAY会提示”下载失败“播放不了

**Comment by somapoke** [comment]
似乎是因为无法正确下载封面导致的，试了下旧版本（2.3.0），该版本不需要显示封面也能播放曲目，虽然也有报错但是可以正常播放

**Comment by toyobayashi** [comment]
有时间再看看

**Comment by toyobayashi** [comment]
找到问题了，原因是新版 UnityFS 格式解包失败了

**Comment by toyobayashi** [comment]
2.6.1 已修复，关闭。

**Comment by somapoke** [comment]
感谢
