### ISSUE TITLE
Download Failed (?)

### ISSUE THREAD

**Issue by meiteki** [toyobayashi/mishiro#4]
Hello! For the past two days i've been unable to launch the desktop app. It's stuck on a loading bar and always says that the download has failed...my internet connection is very stable and it's only been acting up recently. Has anyone else had this problem and can provide a solution?
Sorry if this is reported in the wrong place ><
![image](https://user-images.githubusercontent.com/40902178/42401812-51362938-816f-11e8-890b-81ad1ca2bd7e.png)

**Comment by meiteki** [comment]
Thank you so much for the hard work- i hope it's an easy fix!! ^^

**Comment by toyobayashi** [comment]
Thank you for your reporting. You can download v1.3.5 release now.
