### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by vivipastelito** [toyobayashi/mishiro#41]
![Captura2](https://github.com/toyobayashi/mishiro/assets/129005930/fedad680-895a-4a05-97a1-db2c740b4ea6)
hello!! i know NOTHING about how 2 install these type of apps so id appreciate a bit of help,,, do you maybe have a tutorial or a solution to my problem?

**Comment by toyobayashi** [comment]
"C:\Program Files" requires higher permission to read confoguration file, try to open in administrator or reinstall into your user directory.

**Comment by vivipastelito** [comment]
this fixed it! thank you ^^
