### ISSUE TITLE
unity3d

### ISSUE THREAD

**Issue by vivipastelito** [toyobayashi/mishiro#42]
hello! this is more of a personal issue but i would like to know how do i obtain the 3d models from unity3d files? for example, if wanted to use the cgss models for mmd, how do i extract them? ive been trying unity3d viewers but all they show is code, and im not sure how to get the actual mesh? 
![image](https://github.com/toyobayashi/mishiro/assets/129005930/1449c52e-a026-40a7-8b3d-c1a3975e93c2)
if any confusion was made because of my poor writing, the image above is what i want. only the 3d model, but all i can find is unity3d and i dont know how to get the model out of it, or maybe theres another file type for the 3d model alone? i hope this is not too hard to answer, since ive searched the internet and i cant seem to find an answer. thank you!

**Comment by toyobayashi** [comment]
Sorry, I'm not u3d developer, I'm not aware of what file contains the model and how to extract the model.

**Comment by MarioUniverseZ** [comment]
There's a [documentation](https://www.bilibili.com/read/cv3940742)(in Chinese though) which converts CGSS models into MMD using [AssetStudio](https://github.com/Perfare/AssetStudio), [PmxEditor](https://kkhk22.seesaa.net/category/14045227-1.html)/Blender. you can give it a read

**Comment by lastlament** [comment]
all you need is assetstudio linked in the comment before me, just drag the tx + md files to the assetstudiogui and export. if you need more help, let me know!

**Comment by vivipastelito** [comment]
![image](https://github.com/toyobayashi/mishiro/assets/129005930/13f75ae4-b0f7-4e18-8e8e-61788a8cea09)
thanks everyone for the help, i put mmd as an example because i didnt wanna say something more complicated
(the real reason is im trying to convert these models into vrchat avatars)
months later, i saw this comment and decided to give a try. now, here i am manually moving every single bone so it can make facial expressions! i figured out the assetstudio part, since i already used that program for my projectsekai vrchat avatars. thank u for ur help!
