### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by lastlament** [toyobayashi/mishiro#43]
recent update of Mishiro seems to have assets downloaded improperly(?), many 3d outfits are missing that were there before in previous versions
https://i.imgur.com/qa7B2hY.png

**Comment by toyobayashi** [comment]
mishiro have no update for several years, I didn't play this game for a long time as well. I guess this is caused by game database update itself.

**Comment by NatsukiOkusawa** [comment]
I just took a look at the log file in the resources folder of mishiro and it has the following error:

> [2024-02-27 18:43:12.001] [mishiro] [error] UPDATE getResVer: Error: Error invoking remote method 'checkResourceVersion': Error: 204
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:529)
    at async it (file:///D:/Files/idolmaster/CGSS/mishiro/resources/app.asar/renderer/mishiro.renderer.js:1:110907)
    at async a.getResVer (file:///D:/Files/idolmaster/CGSS/mishiro/resources/app.asar/renderer/mishiro.renderer.js:1:141179)
    at async Dn.<anonymous> (file:///D:/Files/idolmaster/CGSS/mishiro/resources/app.asar/renderer/mishiro.renderer.js:1:144457)

**Comment by toyobayashi** [comment]
@NatsukiOkusawa This is another issue, caused by the game itself server and version update. Need to publish a new release to fix this issue. But I recently have no time to maintain this project, the dependencies is too old so that the project is hard to run locally.

**Comment by NatsukiOkusawa** [comment]
Alright, I see.
Anyway, I did a little experiment where I copied the latest database/manifest files from my phone to mishiro, and it appears like the program can still read the files themselves.

**Comment by karinatarou** [comment]
nice to meet you. I only recently discovered the existence of this app, and I was surprised to see that I wasn't the only one having this problem.
However, I'm not very familiar with the technical use of design and JavaScript, so I'm disappointed that I can't help you...

**Comment by karinatarou** [comment]
nice to meet you. I only recently discovered the existence of this app, and I was surprised to see that I wasn't the only one having this problem.
However, I'm not very familiar with the technical use of Deresute and JavaScript, so I'm disappointed that I can't help you...

**Comment by toyobayashi** [comment]
> I just took a look at the log file in the resources folder of mishiro and it has the following error:

@NatsukiOkusawa OK, in fact it's the same problem with original description of this issue, which is that mishiro fails to fetch the game database. But I still need some time to fix the package process in CI...

<img width="1800" alt="image" src="https://github.com/toyobayashi/mishiro/assets/23353576/44b67e22-0b15-4494-b93d-998d91b954a2">

**Comment by toyobayashi** [comment]
2.7.0 released. feel free to reopen this issue if there is still problem.

**Comment by fukuumocha** [comment]
I have a feeling that some song that have 3dmv assets cannot be found like 8067 (KOI) only have dance but not for stage.
(or I'm too dumb to find it.)
