### ISSUE TITLE
Download All produces unopenable files

### ISSUE THREAD

**Issue by nagi-desuuu** [toyobayashi/mishiro#45]
Downloading the files manually via the home screen produces extract able files when opened in AssetStudio. However, when the same files are downloaded using the Download All function, the files cannot be opened.

**Comment by nagi-desuuu** [comment]
I also forgot to mention that here are the files in question to further prove my point:

|Downloaded from Home page|Downloaded via Download All button|
|---|---|
|[live_atlas_liveui.zip](https://github.com/toyobayashi/mishiro/files/14935456/live_atlas_liveui.zip)|[live_atlas_liveui.zip](https://github.com/toyobayashi/mishiro/files/14935445/live_atlas_liveui.zip)|

(rename .zip to .unity3d because you know github doesn't support direct uploads of .unity3d files)

**Comment by toyobayashi** [comment]
The u3d files in fact are lz4 compressed stored in game server, the home screen downloaded u3d files are auto lz4 decompressed (You can see the `auto lz4 dec` checkbox). The files downloaded via `DOWNLOAD ALL` is the original file (lz4 compressed .unity3d)

**Comment by nagi-desuuu** [comment]
Is it possible that this can also affect Download All?

**Comment by toyobayashi** [comment]
Technically this is not difficult, but I want to say download all is a dangerous feature, which may cause the builtin account be banned. I personally don't recommend to use it, this behavior is expected by design.
