### ISSUE TITLE
Stuck at download/loading screen

### ISSUE THREAD

**Issue by NatsukiOkusawa** [toyobayashi/mishiro#46]
The game just updated and mishiro would get stuck at 'downloading'. This issue is similar to the one encountered years ago.
https://github.com/toyobayashi/mishiro/issues/14

![image](https://github.com/toyobayashi/mishiro/assets/71302813/66cebf11-6baf-4b0e-b156-b134807a743a)

**Comment by toyobayashi** [comment]
Oh! I just saw a new event type in the latest game database.

<img width="734" alt="image" src="https://github.com/toyobayashi/mishiro/assets/23353576/ab5680ed-ba54-401b-a67b-fb9bf3986b38">

The old code behavior don't know where to get it's default BGM (the live tab), so error ocurred. I can fix this if you tell me what .acb file is the default BGM for this event type. I didn't play this game from so long ago and my device have not installed it.

**Comment by toyobayashi** [comment]
Thanks. Let's use `bgm_event_meetup.acb`.

**Comment by toyobayashi** [comment]
2.7.1 released

**Comment by NatsukiOkusawa** [comment]
Thank you very much.
