### ISSUE TITLE
1.4.0 无限读取

### ISSUE THREAD

**Issue by producer95** [toyobayashi/mishiro#6]
![1](https://user-images.githubusercontent.com/42835043/44845920-734d3b00-ac81-11e8-932b-2eef4f701338.png)

**Comment by toyobayashi** [comment]
好像是他服务器的接口变了，我这周末看看

**Comment by producer95** [comment]
感谢，另外还有个小问题，1.4系列新版HOME页面搜索资源点击全选，似乎不能把所有分页的内容都选上

**Comment by toyobayashi** [comment]
@producer95 
其实是有意改成这样的，如果不分页的话，搜出几千上万条数据来会直接卡崩，更别说全选了，这样做是出于性能的考虑，也可以防止批量偷资源的数量过多过快导致被察觉（我猜的

你想批量全选下载什么资源呢？或者有什么修改建议呢？

**Comment by producer95** [comment]
@toyobayashi 
分页确实很好（之前的版本经常卡崩），就是现在每次更新搜索关键词的时候不知道新增的内容在哪页，要一页一页地找，有点麻烦（搜3d贴图就有200+页了。。）

**Comment by toyobayashi** [comment]
@producer95 
更新关键词只会重新搜索包含关键词的记录，是按原本的顺序排的，不会和上一次的搜索结果对比然后定位到有差异的地方，逻辑上也做不到这样。我推荐你先用DB Browser for SQLite打开manifest找到目标文件，再使用mishiro下载。1.4.2版本再次做了性能优化，高速获取u3d文件时不会卡崩了。
