### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ankiramania** [toyobayashi/mishiro#7]
Hi! When I download the newest version of your program (the one you uploaded 14 hours ago), I get an error that says "Error: read ECONNRESET", and nothing will load after that. I can't get in ;__;
![error](https://user-images.githubusercontent.com/42305321/44939538-09519600-ad54-11e8-89a6-0ad801304259.png)

**Comment by toyobayashi** [comment]
@ankiramania The error didn't occurr when I debugged it. I recommend you remove old version completely, then install the newest version and try it again.

**Comment by ankiramania** [comment]
Thank you. It turns out it was a problem with my internet... I apologize for wasting your time.
