### ISSUE TITLE
Could you give a method to get the unity3d model?（能否增加一个获取3d模型的方案）

### ISSUE THREAD

**Issue by aiwonanjing** [toyobayashi/mishiro#8]
想获取原始unity 3d模型，自行研究，但是原来CGSSAssetsDownloader的方法失败了，所以求大佬给个Method.

**Comment by toyobayashi** [comment]
@aiwonanjing I have no idea to get them but how did you do this by CGSSAssetsDownloader? CGSSAssetsDownloader is no longer under maintenance.
我没有任何头绪。。你以前是怎么通过CGSSAssetsDownloader来得到u3d模型的？

**Comment by aiwonanjing** [comment]
在CGSSAssetsDownloader的选项里面有下载3d模型的选项，-o .unity3d，我只是希望这个功能能回来

**Comment by toyobayashi** [comment]
@aiwonanjing If you mean downloading .unity3d files, you can search them on HOME then check the files you need and click download button. You can also use DB Browser for SQLite to find the files first, then download them by mishiro.

如果仅仅是指下载u3d文件的话，你可以直接在HOME里搜索文件名包含的关键字，勾上下载就行了。或者你也可以先用DB Browser for SQLite找一下你要的文件，再用mishiro搜出来下载。

**Comment by aiwonanjing** [comment]
基本算是解决了我的需求了，如果还有办法给3d做分类，我会再开isusue. Thanks.
