### ISSUE TITLE
谱面问题

### ISSUE THREAD

**Issue by srwgin** [toyobayashi/mishiro#9]
能不能在 看谱面和live的界面显示一下时间
设置那做个开关 需要的打开 不需要的关闭
谢谢

**Comment by toyobayashi** [comment]
@srwgin 是指在最下方时间进度条的旁边显示曲子的播放时间吗

**Comment by toyobayashi** [comment]
@srwgin 1.8.3 加上咯

**Comment by srwgin** [comment]
谢谢  看到了
